services:

  vnstat:
    image: vergoh/vnstat:latest
    container_name: vnstat
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/lib/vnstat:/var/lib/vnstat
    environment:
      - RUN_VNSTATD=0
      - EXCLUDE_PATTERN=^docker|^veth|^br-|^lxc
      - HTTP_PORT=8685
      - HTTP_BIND=*
      - HTTP_LOG=/dev/stdout
      - LARGE_FONTS=0
      - CACHE_TIME=1
      - DARK_MODE=1
      - PAGE_REFRESH=60
      - INDEX_IMAGES_PER_ROW=1
      - INDEX_IMAGE_OUTPUT=hs
      - VNSTAT_RateUnit=1
      - VNSTAT_InterfaceOrder=0
      - VNSTAT_QueryMode=0
